/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscaForm.java
 *
 * Created on 04/06/2011, 02:41:32
 */
package br.com.fernandogodoy.sigind.view.buscas;

import br.com.fernandogodoy.sigind.dao.cadastros.ClienteDao;
import br.com.fernandogodoy.sigind.dao.cadastros.ClienteDaoImpl;
import br.com.fernandogodoy.sigind.dao.cadastros.FornecedorDao;
import br.com.fernandogodoy.sigind.dao.cadastros.FornecedorDaoImpl;
import br.com.fernandogodoy.sigind.dao.cadastros.FuncionarioDao;
import br.com.fernandogodoy.sigind.dao.cadastros.FuncionarioDaoImpl;
import br.com.fernandogodoy.sigind.models.cadastros.TipoRelatorio;
import br.com.fernandogodoy.sigind.models.tablemodel.TableModelCliente;
import br.com.fernandogodoy.sigind.models.tablemodel.TableModelFornecedor;
import br.com.fernandogodoy.sigind.models.tablemodel.TableModelFuncionario;
import br.com.fernandogodoy.sigind.models.tablemodel.TableModelUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernado
 */
public class BuscaForm extends javax.swing.JDialog {

    public TipoRelatorio tipoRelatorio;
    public TableModelCliente tmCliente;
    public TableModelFornecedor tmFornecedor;
    public TableModelFuncionario tmFuncionario;
    public TableModelUsuario tmUsuario;

    /** Creates new form BuscaForm */
    public BuscaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public BuscaForm(TipoRelatorio tipoRelatorio) {
        this.tipoRelatorio = tipoRelatorio;
        initComponents();
        setModal(true);
        verificaTable();
        setLocationRelativeTo(null);
        setTitle("Busca de Cliente");
        setVisible(true);
    }

    private void verificaTable() {
        if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_CLIENTE)) {
            tabBusca.setModel(new TableModelCliente(null));
        } else if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_FORNECEDOR)) {
            tabBusca.setModel(new TableModelFornecedor(null));
        } else if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_FUNCIONARIO)) {
            tabBusca.setModel(new TableModelFuncionario(null));        
        } else if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_USUARIO)) {
            tabBusca.setModel(new TableModelUsuario(null));
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBusca = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca de Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Consulta"));
        jPanel1.setEnabled(false);

        jLabel1.setText("Nome:");

        tfBusca.setColumns(50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fernandogodoy/sigind/imagens/searchin.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBuscaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabBusca);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fernandogodoy/sigind/imagens/save.png"))); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_CLIENTE)) {
            ClienteDao dao = new ClienteDaoImpl();
            tmCliente = new TableModelCliente(dao.consultaCliente(tfBusca.getText()));
            if (tmCliente.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não existem fornecedores cadastrados.");
            } else {
                tabBusca.setModel(tmCliente);
            }
        }
        if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_FORNECEDOR)) {
            FornecedorDao dao = new FornecedorDaoImpl();
            tmFornecedor = new TableModelFornecedor(dao.consultaFornecedor(tfBusca.getText()));
            if (tmFornecedor.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não existem fornecedores cadastrados.");
            } else {
                tabBusca.setModel(tmFornecedor);
            }
        }
        if (tipoRelatorio.equals(tipoRelatorio.DETALHAMENTO_FUNCIONARIO)) {
            FuncionarioDao dao = new FuncionarioDaoImpl();
            tmFuncionario = new TableModelFuncionario(dao.consultaFuncionario(tfBusca.getText()));
            if (tmFuncionario.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não existem fornecedores cadastrados.");
            } else {
                tabBusca.setModel(tmFuncionario);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBuscaMouseClicked
        if (evt.getClickCount() == 2) {
            this.dispose();
        }
    }//GEN-LAST:event_tabBuscaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabBusca;
    private javax.swing.JTextField tfBusca;
    // End of variables declaration//GEN-END:variables

    public TipoRelatorio getTipoRelatorio() {
        return tipoRelatorio;
    }

    public void setTipoRelatorio(TipoRelatorio tipoRelatorio) {
        this.tipoRelatorio = tipoRelatorio;
    }

    public TableModelCliente getTmCliente() {
        return tmCliente;
    }

    public void setTmCliente(TableModelCliente tmCliente) {
        this.tmCliente = tmCliente;
    }

    public TableModelFornecedor getTmFornecedor() {
        return tmFornecedor;
    }

    public void setTmFornecedor(TableModelFornecedor tmFornecedor) {
        this.tmFornecedor = tmFornecedor;
    }

    public TableModelFuncionario getTmFuncionario() {
        return tmFuncionario;
    }

    public void setTmFuncionario(TableModelFuncionario tmFuncionario) {
        this.tmFuncionario = tmFuncionario;
    }

    public TableModelUsuario getTmUsuario() {
        return tmUsuario;
    }

    public void setTmUsuario(TableModelUsuario tmUsuario) {
        this.tmUsuario = tmUsuario;
    }
    
    
}
